input_data=open("input.txt","r")#b=int(data[0])  n=int(data[2])  q=int(data[1])
data =input_data.read()
output_data=open("output.txt","w")
data=data.split()
print("введите первый элемент прогресии")
b=int(input())
print("введите множитель прогрессии")
q=int(input())
print("введите номер последнего элемента")
n=int(input())
s=(1-q**n)/(1-q)*b
output_data.write(str(s))
input_data.close()
output_data.close()